### ISSUE TITLE
Make clickable region of OEC Logo identical to SVG size 

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#110]
**Describe the bug**
Clickable area of OEC logo does not match the size of the logo on touchscreen devices (iPad and iPhone 11 at a minimum)

**Expected behavior**
OEC logo clickable area should match the area of the logo.

**Comment by bloom-hondo** [comment]
@admoorgit this is ready for your testing.

**Comment by admoorgit** [comment]
All set! (this was basically fixed when we did the new header — think this was an artifact, but good to review regardless)

**Comment by AmeliaWellers** [comment]
Also looks great
