### ISSUE TITLE
Add https://portal.ct.gov/ hyperlink to Ct.gov logo in header

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#111]
### Context
I have changed my tune to this one. At first I thought it might be confusing to have two clickable logos at the top of the page at all times. Plus, it's hard to find the OEC website from the ct.gov homepage, so I thought users might get lost trying to find their way back. 

But some feedback from the advisory team made me realize that having a non-clickable logo could actually be more confusing. I wanted to confirm with DAS whether making the ct.gov logo clickable is necessary, but I've realized that I already know DAS's answer (yes). 

Additionally, I'll be sending an email to BEST with suggestions to place OEC's resources within the main navigation of ct.gov, so that users can find their way back to OEC more easily than they can now. 

### User Story:
As a [user], I want to be able to navigate to the ct.gov website so that I can find other State of CT resources

### Product Requirements
- User can click on the ct.gov logo
- User is sent to https://portal.ct.gov/ 
- clickable logo SVG has focusable set to = 'false' (aka, user can tab to the logo)

**Comment by bloom-hondo** [comment]
@admoorgit this is ready for your testing

**Comment by admoorgit** [comment]
Perfecto!

**Comment by AmeliaWellers** [comment]
looks great!
