### ISSUE TITLE
Replace homepage logos with CTDS logos 

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#114]
**Issue**: the logos on the homepage are still left over from pre-CTDS times
**Fix**: Replace each logo with the following from the [Icon Library](https://www.ctoec.org/oec-icon-library/)
- Find child care and camps uses the **Family Child Care** 
- Learn abut child development uses **Baby 2 - Swaddled**
- Get parenting support uses **Family 1** (I can't find a better one, but would prefer to not use this icon because it assumes heteronormativity. I know there are two other options, but in this case one icon is needed. Whenever @admoorgit is back, is there a better icon to use here?)
- Get or renew a license uses **Ribbon**
- Get a background check uses **Checklist**

**Comment by admoorgit** [comment]
Yo. I agree with your choices, @AmeliaWellers, and I think for "support" we can just use the heart icon. It's about compassion + empathy, so why not go for it?

@bloom-hondo let me know what you need from me to get this DUNT.

- a.

**Comment by bloom-hondo** [comment]
@admoorgit these are content managed in the home page blocks. you should be able to upload them at will.

**Comment by admoorgit** [comment]
Oh yay! I will look at them this week and update. Will ping you if needed.

**Comment by admoorgit** [comment]
Got em!
@AmeliaWellers I made one change which was to make the child care link show the school building — since it'd be 2 hearts in a row (which was a bit much)
@bloom-hondo can you make the megaphone SVG in the news promo block #54278f? I looked in the block code and didn't see where I could change it.

**Comment by AmeliaWellers** [comment]
This looks awesome now. However, we're missing one! The News megaphone is still black, I assume it should also be purple?

**Comment by AmeliaWellers** [comment]
@admoorgit I'm cool with the above, looks great 

Looking halfway there! For some reason, the handle of the megaphone is black and the megaphone itself is purple! ![Screen Shot 2021-05-11 at 1.24.30 PM.png](https://images.zenhubusercontent.com/600707487eacdcc9a535ffa4/7cb14349-946f-499a-89d9-9f8a8d370600)

**Comment by bloom-hondo** [comment]
On staging
