### ISSUE TITLE
Build ct.gov Header (STAGE) 

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#42]
### User Story
As a website user, I can see and use a fully functional CTDS header across every page of the ctoec.org website, so that I understand that this is a State of CT website.

### Product Requirements
- CT logo is present 
- Google Translation is present and functions across every page in the main navigation
 
### Design requirements
- CT logo is the most up to date logo available
- header matches CTDS design system requirements
- header meets Section 508c accessibility requirements 

### Acceptance criteria
- Header passes QA on live site

### Notes
Refer to business.ct.gov 
1/25: Moved the following User Stories to a later date, after confirming the language translation plans with ct.gov. 
2/2: Confirmed in advisory meeting that English and Spanish are the most common languages, while Brazilian Portugese is the third most popular language. Others include Polish, German, Arabic, Greek and Mandarin, but all are at very small percentages. 

# QA

### QA from Oct 12 2020 (Adam, Browserstack)
Here are the issues I noticed across browsers. There was very little variation in issues, which is a good thing! But there are some areas that need some love:

- [x] Blue bar and alert styling exploded (been consistent across modern browsers too — fixed once I logged into the staging site on said browsers — doesn't work across all older browsers, including mobile) — see screen shot **Most likely a cacheing issue**
- [x] Right margin for expand buttons needs increased. They’re right up against the side of the screen (across all browsers)
- [x] Search bar entry text is bottom-aligned to the search box when active (could be due to styling explosion)
- [x] Search button is larger than the field itself
~~Can we change the “enhanced by GOOGLE” content?~~
- [x] Edge/IE still having some weirdness, but it could also be browserstack:
- [ ] Fonts tend to load slowly on Windows 7 Edge. They are all wrong at first, then site fonts pop into place after a few seconds.
- [ ] Windows 10 Edge pushes the body content to the right — so the whole site is shifted over. See screenshot.

"Alert" toggle is toggleable as "Banner", which can be turned on and off under Appearance > Customize > Header Settings > Banner Settings. Text field can include a hyperlink in the field. Need to work with UW on styling — it's using CTDS styling, and we should adjust to OEC palette.

### QA Checklist ___________________

- [x] Site doesn't timeout unexpectedly
- [ ] Default language is set
- [ ] Page is keyboard accessible and free of keyboard traps
- [ ] Page tab order is logical
- [x] Site never loses focus **except for the ct.gov logo with is perpetually out of focus, notes below**
- [x] Page titles are descriptive
- [x] Headings are nested properly
- [x] Text has sufficient color contrast
- [x] Links are unique and contextual
- [x] All relevant images use an “img” tag
- [ ] All images have alt attributes **the alt attribute for the language image is "office of early childhood", shouldn't it be something like "select language"?**
~~- [ ] Multimedia is tagged~~
~~- [ ] Tables are coded properly~~
~~- [ ] Form inputs have explicit labels~~
~~- [ ] Form instructions are associated with correct inputs~~
~~- [ ] Frames (if applicable) are named~~
~~- [ ] CSS isn't required to use the page~~
~~- [ ] Flashing elements are compliant or set to static~~
~~- [ ] Required plugins are linked on the page~~

**Comment by AmeliaWellers** [comment]
Syncing with @admoorgit  now about how we want to plan our QA, but for now: @bloom-hondo I was clicking around and found an issue with the translation function, which I've created a new issue for. We can release the ct.gov header without it, but if you have the time, it would be great to look over that issue and assess whether you'd have capacity to pull it in for Thursday's release. Otherwise we will roll it into the next sprint.

**Comment by AmeliaWellers** [comment]
@admoorgit I've explored the tools (Axe, web developer, and an accessibility color picker) and checked off the boxes in the list to the extent that I feel comfy speaking to. A few pieces below: 

- Some unnecessary spaces between sentence 1 and sentence 2 in the alert banner
- Not sure if it matters that the div order skips from 4 to  6 between the alert banner and the homepage
- The ct.gov logo is not completely focused. Is there a way to sharpen that image (it looks like a .png, is there an .svg?) 
- The "Connecticut Office of Early Childhood" text within the looks like it's too small to be accessible. Could be worth removing those words, if it helps improve the image quality of the logo.

**Comment by bloom-hondo** [comment]
Fixes have been deployed to https://stage.ctoec.org/

I deleted the caches on the server, but you may need to force refresh your browser.

**Comment by admoorgit** [comment]
**Issue:** Languages drop down only closes when "Languages" text/button, or a link on the page is clicked. 
**Browser(s):** Safari, Chrome, Brave (current vers)
**Suggested Fix:** Allow user to click elsewhere on the page to close it, similar to how the main navigation functions

**Comment by admoorgit** [comment]
**Change:** Adjustment to the "Alert" banner (below the blue bar at the top, above the nav) color palette
**Reason:** The color palette is currently default CTDS, which we've decided to deviate from (as a team, client included) in order to make it more OEC-brand-specific
**Suggested fixes:** remove the border, then — background: #162e51; font-color: #FFF; padding: 1.5rem;

**Question:** What's the dev LOE to add an icon, and 
what's the dev LOE to add the ability for a user to close the alert?

Thanks!
- a.

**Comment by admoorgit** [comment]
**Issue:** "Scroll to Top" does not scroll to include the navigation or CT bar — it stops just above the breadcrumb
**Suggested fix:** Add anchor link to header

**Comment by admoorgit** [comment]
**Issue:** "Languages" button is not accessible via keyboard (tab skips from "skip to main content" link to the "alert" link)
**Suggested fix:** Make "Languages" keyboard accessible — between "skip to main content" and "alert"/OEC logo

**Comment by admoorgit** [comment]
Update on Skylight checklist items:

**[N/A]** Multimedia is tagged
**[N/A]** Tables are coded properly
**[N/A]** Form inputs have explicit labels
**[N/A]** Form instructions are associated with correct inputs
**[N/A]** Frames (if applicable) are named
**[N/A]** CSS isn't required to use the page
**[N/A]** Flashing elements are compliant or set to static
**[N/A]** Required plugins are linked on the page

**Comment by admoorgit** [comment]
**Minor quirk:** "Menu" active state has slightly less padding than it's hover state, so it shrinks on click. Cosmetic only. Not a blocker for launch.

**Comment by admoorgit** [comment]
**IE11 / Windows 7 issue:** "Languages" globe icon is permanently squished. Very small user base, and visual quirk only. Not a blocker for launch.

**Comment by admoorgit** [comment]
**CLIENT QUESTION:** 
Do want the CT.gov logo in the new header to link to CT.gov, or to CTOEC.org?

**Note:** OEC logo links to the homepage currently.

@admoorgit I thought about this too. In an effort to stay as simple as humanly possible for this first launch, having a static image seemed to be the least risky move. Other reasoning: when a user clicks the ct.gov logo, they're exiting the OEC website, which seemed jarring, and begs some user testing. Also, the OEC logo and ct.gov logo are pretty close together which seems like it could challenge some users, especially on mobile. 

Of course, if we get feedback that it should be clickable, we can have the convo with them about what that means from a user standpoint. For this first pass at least, it felt safest to not let the CTDS brand change govern so much of the website's function.

**Comment by AmeliaWellers** [comment]
**Issue**: in mobile and tablet view, horizontal white border is displayed between each language selection in the dropdown. 
**Browser**: Chrome, Safari
**Suggested Fix**: change white line color to CTDS blue to make them invisible, or remove white lines.

**Comment by AmeliaWellers** [comment]
Something to watch out for when the ct.gov header is viewed on the translation bar: right now, the language translation overlaps the header of the alert banner when viewed in mobile. 
Browser: Chrome (viewed in Windows)

![Screen Shot 2021-02-10 at 12.46.57 PM.png](https://images.zenhubusercontent.com/600707487eacdcc9a535ffa4/04f86df3-9183-4b07-aece-1bc122e00304)
