### ISSUE TITLE
From Oct 2020: All SVGs have focusable = 'false'

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#52]
From Adam: OEC logo, globe icon, mag glass SVGs are coming up as focusable. ARC Toolkit recommends set focusable=‘false’. This may be irrelevant due to other code, but wanted to flag just in case.

**Comment by admoorgit** [comment]
Hi!
The original ask for this has been resolved with header updates. So yay!
Here are a few things I've noticed on the homepage and footer in Safari specifically, @bloom-hondo :

- Footer SVG logos don't visibly focus when tabbed to (OEC and CT.gov), but their links work
- Links in the "Get practical help for your family" and "Build your career in early childhood" do not have a visible focus state on tab either, but their links work

Considering every other item has a visible focus, I'd reckon these should too.

- a.
