### ISSUE TITLE
News Page Design Improvements

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#54]
### Context 
This epic has been changing over time, but is intended to cover all of the news page tweaks needed to update the out-of-the box core functionality. Many of the initially identified tweaks (adding pagination and dates to the news page) were added in the Fall.

### List of tweaks: 
- [News page Styling Inconsistencies](https://app.zenhub.com/workspaces/oec-website-product-board-600732ace98820000e3ffaea/issues/ctoec/ctoec/80)
- [Remove Featured News Text Box from news post editor](https://app.zenhub.com/workspaces/oec-website-product-board-600732ace98820000e3ffaea/issues/ctoec/ctoec/98)
- [Add date range filter](https://app.zenhub.com/workspaces/oec-website-product-board-600732ace98820000e3ffaea/issues/ctoec/ctoec/99)
- [Update the background color/styling of the dropdown filter.](https://app.zenhub.com/workspaces/oec-website-product-board-600732ace98820000e3ffaea/issues/ctoec/ctoec/100)

**Comment by admoorgit** [comment]
Updates for news page:

• H1 to match rest of site
• Left nav cap to match rest of site
• Updated expand view (make a callout!)
• Updated pagination style (next sprint?)

![News.png](https://images.zenhubusercontent.com/60074627e5960a2e82af8ecd/f8d3d16c-d2f7-4c4a-abd9-c98ec8fb56d3)
![News Expanded.png](https://images.zenhubusercontent.com/60074627e5960a2e82af8ecd/2babb38c-b7f0-44d6-b87c-c21223d75044)
