### ISSUE TITLE
Tables on CTOEC are wrapped in a <figure> tag with its own class.

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#58]
**Describe the bug**
Tables on CTOEC are for some reason being wrapped in a figure tag with it's own class.

In the Fall 2020, solution was found by Adam, Leo or Jesse when this ticket was moved into the sprint in December. Moved back to backlog and waiting for front-end dev's 2 cents. 

**To Reproduce**
1. Go to any page that has a table
2. Click on the table and press "inspect element"

**Expected behavior**
 It should be the "usa-table" style exclusively.

**Additional context**
Potential: reach out to Gutenberg to share difficulties of working around tag. 
[Figure Tag](http://bit.ly/OECWebsiteTrello)

**Comment by bloom-hondo** [comment]
This is the standard behavior for WP blocks. The styles for the wp-block-table class get applied from usa-table, so it should be okay.

**Comment by AmeliaWellers** [comment]
Making sure @admoorgit sees Matt's comment above... if all good, will move to done (thank you for investigating, Matt).

**Comment by admoorgit** [comment]
I did see this! Checked how tables display on the site now and it looks like the problem is fixed. The problem was border-collapse was weird and all the cells were split out. Looks like they're behaving now. Yay? YAY!
