### ISSUE TITLE
Videos are not loading on webpages

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#62]
**Describe the bug**
Videos are not loading on webpages. See the [For Families, By Families](https://www.ctoec.org/for-families-by-families-keep-it-real-initiative/) page as an example.  

**Expected behavior**
Videos should be visible.

**Screenshots**
[Screen Shot 2021-01-27 at 5.43.53 PM.png](https://images.zenhubusercontent.com/600707487eacdcc9a535ffa4/abe2aac3-b82c-4b97-baea-9869f9e9ed3e)

**Desktop**
 - Browser [e.g. chrome, safari] ---- replicated the issue on Chrome across mobile, tablet and desktop.

**Additional context**
Could be related to the issue about images being stretched vertically. 
Amelia deleted one of the videos, created a new video content block, and added the YouTube URL in again to test if the content block just needed some manual updating. It did not make a difference.

**Comment by AmeliaWellers** [comment]
Team troubleshooting on 1/27/20 6pm
- Confirmed that videos are viewable on Chrome, iPhone for safari, Firefox and edge. 
- Amelia wasn't able to see the videos even after a cleared Google Chrome Cache, cleared WordPress cache, and force refresh of the site. When she managed to logout and do a force refresh, it worked :)

**Comment by mta-hondo** [comment]
Videos were broken. Anyone who was seeing them was on a cached version of the page. This is fixed though.

**Comment by bloom-hondo** [comment]
Anyone who was able to see this was viewing a cached version of the page. It should be resolved now.
