### ISSUE TITLE
"In this section" does not toggle to secondary nav

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#67]
**Describe the bug**
On iOS, and in mobile view on the chrome browser, the "In this section" widget briefly shows the second nav and then disappears. The menu does not show again when clicking "in this section", though the arrow toggles down, and up, and changes from grey to blue.

**To Reproduce**
1. Go to any secondary nav page on the website. 
2. Click on "In this section" 

**Expected behavior**
The secondary navigation should be visible and each page should be selected.

**Screenshots**
![IMG_2224.PNG](https://images.zenhubusercontent.com/600707487eacdcc9a535ffa4/04052f45-8bc9-4b8a-b6fd-67f7a15bced5)

**Smartphone (please complete the following information):**
- Device: iPhone 11
- OS: iOS
 - Browser: Chrome and Safari

**Additional context**
Wasn't there a problem like this a few months ago too? Is this something UW should be privy to?

**Comment by bloom-hondo** [comment]
Ready to test on production

**Comment by AmeliaWellers** [comment]
I tested the majority of menu items on my iPhone 11, looks good!
