### ISSUE TITLE
Build Icon Library (STAGE)

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#74]
### User Story
As an OEC Staff member, I am able to use choose from multiple icons when creating a callout box, providing additional options to visualize the purpose or topic of the message I'd like to share. 

### Product Requirements
- user can only use the icon library from callout boxes
- When selecting "~change~ select icon" in a callout box, user can see the full icon library

### Design Requirements
- All icons use OEC purple **Didn't happen, but the black doesn't look bad and is in line with CTDS reccs**
- Icons match CTDS (https://ionicons.com/)
- icons have alt text -- **Discussed in sync that this isn't necessary**
- Icons scale across browser sizes and never lose focus or alignment
- icon sizes remain consistent across vertical or horizontal callout boxes

### Acceptance Criteria
- Full icon library is displayed and selectable **discussed in sync that this is not possible due to dev hours**
- Icons meet all accessibility and design requirements

# QA Checklist 
- [x] Amelia moves QA checklist to each user story/issue 
- [x] Round 1a: Amelia tests functions and as much accessibility as possible, report findings in ticket
- [ ] Round 1b: Adam tests functions and finishes accessibility checklist, report findings in ticket
- [ ] Round 2: Matt updates stage, Amelia and Adam confirm bug fixes in stage

## Product / Function
- [x]  meets product requirements
- [x]  meets design requirements 
- [x]  meets acceptance criteria (user story) 
- [x]  additional functions or use cases tested: 
  - [x] User can add or remove an icon from the icon library
  - [ ] 

## Accessibility
- [x] *Icons* never loses focus
- [x] *Icons* have sufficient color contrast
~- [ ] All relevant images use an “img” tag~
~- [x] All images have alt attributes *(but they don't show when inspecting element)*~
- [ ] Multimedia is tagged
- [ ] Frames (if applicable) are named
- [ ] CSS isn't required to use the page
~- [ ] Site doesn't timeout unexpectedly~
~- [ ] Default language is set~
~- [ ] Page is keyboard accessible and free of keyboard traps~
~- [ ] Page tab order is logical~
~- [ ] Page titles are descriptive~
~- [ ] Headings are nested properly~
~- [ ] Links are unique and contextual~
~- [ ] Tables are coded properly~
~- [ ] Form inputs have explicit labels~
~- [ ] Form instructions are associated with correct inputs~
~- [ ] Flashing elements are compliant or set to static~
~- [ ] Required plugins are linked on the page~

### Mac
- [x] OS Catalina - Safari 13, Chrome 88, 87 (Amelia)
- [ ] OS Big Sur - Safari 14, Chrome 88, 87 (Adam)
### Windows 10 (Adam)
- [ ] Edge 88
- [ ] Safari 14, 13
- [ ] Chrome 88, 87 
- [ ] IE 11
### iOS (Amelia), alternate testing in safari and chrome
- [x] iPhone 12
- [x] 12 Pro Max
- [x]  XR
- [x] 11
- [x] 8
- [x] Mini
- [x] SE
iPad
- [ ] iPad Air  - server wasn't responding
- [ ] iPad Pro 12 - server wasn't responding
### Android (Adam) 
- [ ] Galaxy S9

**Comment by admoorgit** [comment]
Hi!
Icons are stored here: [https://drive.google.com/drive/folders/1879G-wbvsJCfKzp8Mi7XwqMBHSSVftVO?usp=sharing](https://drive.google.com/drive/folders/1879G-wbvsJCfKzp8Mi7XwqMBHSSVftVO?usp=sharing). First batch is in there, and I'll continue to add and remove as needed. As of now there are A LOT (probably too many), so I'll talk to content about what makes sense given the needs they've seen so far.

Tagging @MorganGriffin-BloomWorks to get that convo started.

**Comment by admoorgit** [comment]
Update: Morgan cleaned some icons out (they're in a folder called "Consider removing" for now), and I did a second pass to get the number down. We have 90 icons now, which seems to cover a ton of bases. I think we're in a good spot to load these in.

https://drive.google.com/drive/folders/1879G-wbvsJCfKzp8Mi7XwqMBHSSVftVO?usp=sharing

**Comment by AmeliaWellers** [comment]
Sweet - I took a look and they all look normal - except for the woman icon? Is she reading a book? Is there a normal one? 
https://drive.google.com/file/d/1FxGUTVZ44arob11x3NIGbSQ5ZsAXdNl4/view?usp=sharing

**Comment by admoorgit** [comment]
I THINK that's a preview issue, as "she" doesn't have a book. I'll look at the anchors and make sure all the paths are drawn. Likely something is missing

**Comment by admoorgit** [comment]
YUP. Anchors weren't connected. Might've caused issues with the SVG display on the site itself, so glad you called it out. Should preview OK now.

**Comment by AmeliaWellers** [comment]
- I uploaded all of the icons from the drive file into Stage. Nothing broke when I uploaded all 50 icons, but it did take about a half hour (note for release timing)

### Product/Functionality
 - since we can't see the full icon library visualized, Matt is looking into a scroll bar for the list of icon titles. If this is possible, product reccs are met. 

### Design/Accessibility
- I added Alt text to the Wrench and Alarm icons, to make sure it functions. It is possible, but it doesn't show in Axe/html
- Icons are not purple, but black looks good too and conforms with CTDS. Up to @admoorgit if he'd like to update icon library to purple. 
- aside from the above, design reccs are met
- I didn't add the custom icons yet - not sure if @admoorgit was finished. This can happen at any time outside of the release as well.
