### ISSUE TITLE
ct.gov header bug fixes

### ISSUE THREAD

**Issue by admoorgit** [matthewcrist/ctoec#77]
### Issue
**Issue:** "Languages" button is not accessible via keyboard (tab skips from "skip to main content" link to the "alert" link)
**Suggested fix:** Make "Languages" keyboard accessible — between "skip to main content" and "alert"/OEC logo
- [x] Ready for QA
- [ ] Confirmed Fixed
- [ ] Added to production

~### Issue~
~**Issue**: the alt attribute for the language image is "office of early childhood"~
~**Suggested Fix**: replace alt attribute with "select language~

### Issue
**Issue**: Languages drop down only closes when "Languages" text/button, or a link on the page is clicked.
**Browser(s)**: Safari, Chrome, Brave (current vers)
**Suggested Fix**: Allow user to click elsewhere on the page to close it, similar to how the main navigation functions
- [x] Ready for QA
- [x] Confirmed Fixed
- [x] Added to production

### Issue
**Issue**: in mobile and tablet view, horizontal white border is displayed between each language selection in the dropdown. 
**Browser**: Chrome, Safari
**Suggested Fix**: change white line color to CTDS blue to make them invisible, or remove white lines. 
- [x] Ready for QA
- [x] Confirmed Fixed
- [x] Added to production

**Comment by AmeliaWellers** [comment]
@admoorgit found this at the bottom of the Icebox column? Is this for Release 1 or Release 2?

**Comment by admoorgit** [comment]
Release 1. Is complete!

**Comment by AmeliaWellers** [comment]
@bloom-hondo the Languages menu can now be tabbed to (hooray), but the menu cannot be selected by pressing "enter" on the keyboard. 
fix: ensuring user can tab through all languages selections on the menu bar, select each one by pressing "enter", and can close/tab out of the dropdown

**Comment by AmeliaWellers** [comment]
Moving this last bug to a new ticket for the next release, and movin this one to done :)
