### ISSUE TITLE
News Page Styling Inconsistencies - round 1

### ISSUE THREAD

**Issue by admoorgit** [matthewcrist/ctoec#80]
**Describe the issue**
It's not a bug, it's just a styling issue.
News page (https://www.ctoec.org/news) and individual news items (https://www.ctoec.org/news/read-oecs-new-handout-about-promoting-well-being-during-covid-19/, for example) use the wrong left nav, and the wrong H1 tags.

**To Reproduce**
1. Go to the links above

**Expected behavior**
Proper use of left nav and H1

**Screenshots**
![Screen Shot 2021-02-10 at 11.11.53 AM.png](https://images.zenhubusercontent.com/60074627e5960a2e82af8ecd/fdf3ab00-741d-4571-9fb3-a3aeee26d175)

![Screen Shot 2021-02-10 at 11.10.46 AM.png](https://images.zenhubusercontent.com/60074627e5960a2e82af8ecd/f1771131-95e2-41d6-a32c-14557479bf9c)

**Desktop (please complete the following information):**
 - All

**Smartphone (please complete the following information):**
 - All

**Additional context**
This may be something I can look into to save Matt some time.

**Comment by AmeliaWellers** [comment]
Looks much better to me!

**Comment by AmeliaWellers** [comment]
I complete missed this in my QA, but I've just realized: 
- The news page's title is "About" but it should be "Our Work" 
- The news page's sidebar heading is H2, whereas all other sections' sidebar headers are H3. I don't know if this is a big deal, but flagging just in case, and we may as well keep it consistent and have all sidebar titles at H3.

**Comment by admoorgit** [comment]
Hello! Here are my suggestions for tweaks for the page.

- @AmeliaWellers you are right — sidebar header should be H3 size/style, not H2
- Let's get a little more padding underneath the "filter results" button. I changed the div class to "margin-bottom-7" and that looked good!
- On the pages that have the news injected into them, a few tweaks to the "Latest News" H2 — Remove top margin, and add 2.75rem padding below
- I don't recall why we went with H3 size for news links but they come off huge outside the home page. I'm fine changing them to normal <p> tag size
- Can we add a calendar icon to the "From" and "To" fields? There's one in the icon library. This will help set expectation for the user for the function of the click. Also — do we have any thoughts on placing them side-by-side like popular travel sites (for recognition), or is that an accessibility no-no?
- "NEW" tags shift the separator lines over to the right, which looks kinda funky when items below don't have them. Consider stacking "New" in top of content, or adding the same rules above and below so it's seamless
- Should we add a "cancel" button to the right of the "Search" button in case a user decides not to search? It'll save em a scroll
- Close menu when content loads after user clicks "Search" – currently it remains open
- Do we have any plans to implement tags to show what items were selected in the Filter menu? Since we've removed the categories from the read-out, there is now no indication of what is showing on the page, or what the user selected unless the menu is open

I think that covers it! We can chat more at meetings
- a.

**Comment by AmeliaWellers** [comment]
@admoorgit and I walked through the pieces above on the news page, and condensed them. I've listed and prioritized them here. Adam, would you mind sharing an updated mockup below? 

-  Please add the categories beneath each ctoec.org/news news item (thanks Adam for catching this!). When removing the categories on the homepage (they didn't serve a purpose there), we also accidentally removed the categories on the news page (where they do serve a purpose, especially for filtering). 
- A user should be able to clear the filter without re-opening the filter tab. Add "clear filter" as clickable text underneath "filter results" tab
- Ensure H3 tag for Our Work sidebar
- Extend the horizontal separator (border-bottom) to the full width 
- shrink the size of the Hyperlinked News titles to regular link size (fx: same text size as sidebar)
- QA: make sure the news filter closes after pressing Search (at least on safari)

**Comment by AmeliaWellers** [comment]
On second thought, I want to keep all the news edits in the same place to reduce confusion. I am closing this ticket (it will refer to only Sprint 5 news style fixes now), and moving the exact comment above into the "[News Filter Issues](https://app.zenhub.com/workspaces/oec-website-product-board-600732ace98820000e3ffaea/issues/ctoec/ctoec/118)" ticket that is currently in the backlog, renamed to "News Issues"
