### ISSUE TITLE
CSS Style changes are added to STAGE 

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#82]
### Design Requirements
[Feb 2021 Mockup](https://www.figma.com/file/YifRehO7BrZhP1Wdru67Zo/CTDS-OEC?node-id=280%3A0 )

### Acceptance Criteria
- [x] CSS Style changes have been added to the staging environment
- [ ] CSS Style changes meet Product/Design requirements

### Resources
[October 2020 Mockup](https://trello-attachments.s3.amazonaws.com/5c17dc735e6e6c1c9e791dfc/5eeb738ba7298126c010ec43/282de4e2112d7160af93ef545d2f5867/CTDS%2BOEC.jpg)

# QA Checklist 
- [x] Amelia moves QA checklist to each user story/issue 
- [x] Round 1a: Amelia tests functions and as much accessibility as possible, report findings in ticket
- [x] Round 1b: Adam tests functions and finishes accessibility checklist, report findings in ticket
- [x] Round 2: Matt updates stage, Amelia and Adam confirm bug fixes in stage

## Product / Function
- [ ]  meets product requirements
- [ ]  meets design requirements 
- [ ]  meets acceptance criteria (user story) 
- [ ]  additional functions or use cases tested: 
  - [ ] 
  - [ ] 

## Accessibility
- [x] Site doesn't timeout unexpectedly
- [x] Default language is set
- [x] Page is keyboard accessible and free of keyboard traps
- [x] Page tab order is logical
- [x] Site never loses focus
- [ ] Page titles are descriptive
- [ ] Headings are nested properly
- [x] Text has sufficient color contrast
- [x] Links are unique and contextual
- [x] All relevant images use an “img” tag
- [x] All images have alt attributes
- [x] Multimedia is tagged
- [x] Tables are coded properly
- [x] Form inputs have explicit labels
- [x] Form instructions are associated with correct inputs
- [x] Frames (if applicable) are named
- [ ] CSS isn't required to use the page
- [x] Flashing elements are compliant or set to static
- [x] Required plugins are linked on the page

### Mac
- [x] OS Catalina - Safari 13, Chrome 88, 87 (Amelia)
- [ ] OS Big Sur - Safari 14, Chrome 88, 87 (Adam)
### Windows 10 (Adam)
- [ ] Edge 88
- [ ] Safari 14, 13
- [ ] Chrome 88, 87 
- [ ] IE 11
### iOS (Amelia)
- [x] iPhone: 12, 12 Pro Max, XR, 11, 8, Mini SE
  - [x] Safari 14, 13
  - [x] Chrome 88, 87 
- [ ] iPad 12 (check resolution!)
  - [ ] Safari 14, 13
  - [ ] Chrome 88, 87 
### Android (Adam) 
- [ ] Galaxy S9

### Full accessibility checklist
https://skylight.digital/work/toolkits/accessibility-guide/checklist/

**Comment by admoorgit** [comment]
Here B CSS Style Changes 4U @bloom-hondo :

H1 (this is for pages with NO hero image)
~~font-size: 3.5rem; (approx 56px)~~
**font-size: 3rem;**
**margin-bottom: 1rem;**
font-weight: bold;
color: #fff
**line-height: 1.15;**

H2 
~~font-size: 2rem (approx 32px)~~
**font-size: 1.75rem;**
font-weight: bold;
color:  #61366F;
line-height: 1.25;
~~margin-top: 1.5rem
margin-bottom: .75rem~~
**margin-top: 2.75rem;**
**margin-bottom: .25rem;**


H3
~~font-size: 1.65rem; (approx 26px)~~
**font-size: 1.4rem;** 
font-weight: bold;
color: #1b1b1b;
line-height: 1.25;
~~margin-top: 1rem;~~
~~margin-bottom: .5rem;~~
**margin-top: 1.5rem;
margin-bottom: .25rem;**


H4
**font-size: 1.3rem;**
font-weight: bold;
color: #61366F;
Line height = 1.25;
**margin-top: 1.25rem;
margin-bottom: .25rem;**

H5
**font-size: 1.25rem;** 
font-weight: bold;
color: #1b1b1b;
Line height = 1.25;
**margin-top: .75rem;
margin-bottom: .25rem;**

H6

**font-size: 1.2 rem;**
font-weight: bold;
color: #61366F;
Line height = 1.25;
**margin-top: .75rem;**
margin-bottom: .25rem;

P
font-size: 1.125rem; (approx 18px)
font-weight: regular;
color: #1b1b1b;
Line height = 1.75
margin-top: .5rem;
margin-bottom: .5rem;

UL
font-size: 1.125rem; (approx 18px)
font-weight: regular;
color: #1b1b1b;
Line height = 1.75;
margin-top: 0;
margin-bottom (last bullet only): 1rem;
(indent is the same as it is currently)

.ct-callout-title
font-size: 1.5rem; (approx 24px)
font-weight: 700;
color: #1b1b1b;
Line height = 1.25;
margin-bottom: .5 rem;


**MISC**

**.bg-footer**
+ margin-top: 5rem;

**.ct-callout--horizontal .ct-callout-card**
border-left-width (or top-width on card): .375rem solid #61366F  (7px)

**.usa-prose>table thead td, .usa-prose>table thead th, .usa-table thead td, .usa-table thead th, .wp-block-table table thead td, .wp-block-table table thead th** 
border-color: #CACACA; (or whatever our medium grey currently is — this will be the border color on all tables)
color: #000;
background-color: #61366F;
(so,  purple headers w/ white text, and lighter border colors

**Comment by admoorgit** [comment]
Updated H-tags with new values for @bloom-hondo. Less horsey overall, more spacing added in.

**Comment by AmeliaWellers** [comment]
Hola! I did a brief QA, a few thoughts below: 
- It looks like the table CSS updates didn't make it into stage 
- Browserstack isn't really working this morning, I'll try the full QA later today
-  I'm not sure the CSS it's made its way to all of the pages? [This](https://stage.ctoec.org/covid-19/coronavirus-covid-19-faq/) feels differently grouped than [this](https://stage.ctoec.org/child-development/)? 

Secondly, I wanted to see it on staging first before I could articulate:  I would vote for keeping the headers all the same black color. My reasoning is: 
  - My brain wants there to be a functional reason behind why one header is purple, and why one is black. Since all headers have the same function to segment and nest content, I want to either group all purple headers and black headers (which doesn't make sense since they are alternating H tags), or, click on the purple headers and not the black headers. 
   - since the H tag nesting is different for each page, the alternating header colors makes each page feel less consistent across the site.  For example, a header that asks a question can have either a purple or black header depending on the page, but it's not clear why. For example, the purple headers play the same role[ on this page ](https://stage.ctoec.org/school-readiness-preschool-grant-program/)as black headers[ on this page](https://stage.ctoec.org/covid-19/coronavirus-covid-19-faq/)

**Comment by AmeliaWellers** [comment]
Ah additionally - were the alert banner changes (shortening the height) planned to be included in this css list? I don't think I see it in the list of CSS styles, but I could be missing it.

**Comment by AmeliaWellers** [comment]
@admoorgit making sure you've seen the above in time for us to make changes before our thursday release. Additionally, @bloom-hondo it looks like the tables still haven't been updated with new styles in stage

**Comment by admoorgit** [comment]
Hello! I have responses for you @AmeliaWellers!

- @matt do you need anything for table CSS updates from me?
- There shouldn't be anything to look at in browserstack, tbh, since there's nothing fancy or special about the changes — but for the sake of due diligence have at!
- It's all in there, it's just how the pages are tagged. Some are tagged weird, [like this page](https://stage.ctoec.org/covid-19/coronavirus-covid-19-faq/). The questions don't need to be H3s, so really the subcategories should be H3 ... not weirdly H4. I will fix this on live if it's tagged similarly.

Response re: header colors:
- Purple vs. Black headers is intended to make the difference clearer faster for sighted users — purple (H2) = main section on the page, black = sub section. That said, pages across the site seem to be inconsistently tagged, so it's a bit of an issue.
- I'd be OK making ONLY H2s purple, and the rest black. That will go a long way toward consistency.

Let's chat about it at planning meeting today!
- a.

-

**Comment by admoorgit** [comment]
Hi!
Oooo nice changes @bloom-hondo! Here are new tweaks to wrap things up:
• Let's make the ONLY H-tag with #61366F H2. So H3-H6 are all #1b1b1b. Good call @AmeliaWellers.
• Would like a little some tweaks to H3s. In Inspector I set it to: "margin-top: 1.75rem;" and
"line-height: 1.25;" and things looked good to me. So whatever that translates to in real life, that'll work.

That's it!
