### ISSUE TITLE
Build Hero Image Component as Featured Image

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#83]
### User Story:
As a staff member, I want to be able to add a hero image to the page in order to more quickly set a pleasing visual tone for selected pages. 

### Product Requirements
- [x]  Users can upload an image using the "Featured Image" setting
- [x] Users can upload a single image from their computer
- [x] Users can select a single image from the media library (?)
- [x] Users can change and replace an image (selecting a new image from their computer or the media library)
- [x] Users can see the image they have selected in the Featured Image thumbnail in the sidebar
- [x] Users only need to type the title of the page once at the top of the page editor

### Design Requirements
- [x]  If a user uploads an image, the title of the page overlays the hero image and does not display at the top of the body of content
- [x] OEC Purple gradient always stays on the left 
- [x] Featured Image fits and scales across dimensions with the header 
- [x] Images are not obscured by the purple heading overlay
- [x] Featured Image heading text is white and remains as an H1 tag
- [x] Minimum image dimensions and resolution: 
- [ ] Maximum image dimensions and resolution:

### Acceptance Criteria
- User reccs are met
- Design reccs are met
- user can preview and publish a page using a hero image

### Resources
[Comp/Mockup from October 2020](https://trello-attachments.s3.amazonaws.com/5c17dc735e6e6c1c9e791dfc/5eeb738ba7298126c010ec43/282de4e2112d7160af93ef545d2f5867/CTDS%2BOEC.jpg)

# QA Checklist 
- [x] Amelia moves QA checklist to each user story/issue 
- [x] Round 1a: Amelia tests functions and as much accessibility as possible, report findings in ticket
- [x] Round 1b: Adam tests functions and finishes accessibility checklist, report findings in ticket
- [x] Round 2: Matt updates stage, Amelia and Adam confirm bug fixes in stage

## Product / Function
- [x]  meets product requirements
- [x]  meets design requirements 
- [x]  meets acceptance criteria (user story) 
- [ ]  additional functions or use cases tested: 
  - [ ] 
  - [ ] 

## Accessibility

- [x] Page is keyboard accessible and free of keyboard traps
- [x] Page tab order is logical
- [x] Site never loses focus
- [x] Headings are nested properly
- [x] Text has sufficient color contrast
- [x] All relevant images use an “img” tag
- [x] All images have alt attributes
- [x] Multimedia is tagged
~- [ ] Frames (if applicable) are named~
~- [ ] Tables are coded properly~
~- [ ] Form inputs have explicit labels~
~- [ ] Form instructions are associated with correct inputs~
~- [ ] CSS isn't required to use the page~
~- [ ] Flashing elements are compliant or set to static~
~- [ ] Required plugins are linked on the page~
~- [ ] Site doesn't timeout unexpectedly~
~- [ ] Default language is set~
~- [ ] Page titles are descriptive~
~- [ ] Links are unique and contextual~

### Mac
- [x] OS Catalina - Safari 13, Chrome 88, 87 (Amelia)
- [x] OS Big Sur - Safari 14, Chrome 88, 87 (Adam)
### Windows 10 (Adam)
- [x] Edge 88
- [x] Safari 14, 13
- [x] Chrome 88, 87 
- [x] IE 11
### iOS (Amelia)
- [x] iPhone: 12, 12 Pro Max, XR, 11, 8, Mini SE
  - [x] Safari 14, 13
  - [x] Chrome 88, 87 
- [x] iPad 12 (check resolution!), and 8th Gen (GEER ipads)
  - [x] Safari 14, 13
  - [x] Chrome 88, 87 
### Android (Adam) 
- [x] Galaxy S9

### Full accessibility checklist
https://skylight.digital/work/toolkits/accessibility-guide/checklist/

**Comment by bloom-hondo** [comment]
@admoorgit i need the css gradient specs for the hero

**Comment by admoorgit** [comment]
Hola!
Here's an approximation of what's going on in Figma:
- linear-gradient(to right, rgba(97,54,111,1), rgba(97,54,111,0));
- mix-blend-mode: multiply
- the gradient itself is about 75% of the image.

If it'd be easier + more supported to use an SVG, I can generate one of those too. Let me know which you prefer.

**Comment by AmeliaWellers** [comment]
**Bug:** In OS Catalina on Safari, hero image is stretched vertically, and it looks like CSS is stripped (no gradient, header is above the background image). ![Screen Shot 2021-03-04 at 2.41.13 PM.png](https://images.zenhubusercontent.com/600707487eacdcc9a535ffa4/6512e716-331c-4731-92b2-0b73b0bf32fc)

(and yes, I cleared all the caches :)

**Comment by AmeliaWellers** [comment]
**Bug:** If an uploaded featured image is too small, a blue alert bar displays underneath the featured image thumbnail. The image obscures the alert so that it cannot be read.  Screenshot below.

**Addtl. considerations:** There is is also an alert banner that displays at the top of the page when a too-small image is uploaded (screenshot also below). For this first round, I think it's ok to have one warning/alert displayed, especially because a user cannot publish the page anyway. 

**Suggested fix:** Keep the banner alert that displays in the page editor. Remove the blue thumbnail alert. 

Thumbnail alert:
![Screen Shot 2021-03-04 at 5.10.42 PM.png](https://images.zenhubusercontent.com/600707487eacdcc9a535ffa4/4acb3604-c2f9-4b4f-85ca-ab33c617dea4)

Banner alert in page editor:
![Screen Shot 2021-03-04 at 5.42.34 PM.png](https://images.zenhubusercontent.com/600707487eacdcc9a535ffa4/f099a540-26b0-47a1-a57a-ff66f9754040)

**Comment by AmeliaWellers** [comment]
**Bug (kinda):** Somewhat related to the "obscuring image" design requirement, some of these images may not be scaled or oriented appropriately for the banner. For example, you can't see the man's eyes in the desktop view, and he's a half-purple human  in mobile.
**One idea:** We could start custom cropping each header image when Adam and I start to upload images, but that may significantly reduce the image size. @admoorgit taking any or all ideas, I know you've mentioned this in passing during a past conversation. 

Screenshot example [on this page](https://stage.ctoec.org/about-oec/?preview_id=3351&preview_nonce=c5b83fbc44&preview=true&_thumbnail_id=13200): 
![Screen Shot 2021-03-04 at 5.50.00 PM.png](https://images.zenhubusercontent.com/600707487eacdcc9a535ffa4/0c50c0e4-d83c-48ca-9cb8-d5baef3bc293)
![Screen Shot 2021-03-04 at 6.04.30 PM.png](https://images.zenhubusercontent.com/600707487eacdcc9a535ffa4/4084d2d2-70e4-4f9b-a709-d1234986152b)

**Comment by admoorgit** [comment]
Helloooo,
@AmeliaWellers — I figure for this first set (at the very least), we'll crop all of the images by hand. Won't take long to do with Figma! Part of my review of the images currently on the site was seeing how they'd crop in this new config. Not all of them will work as-is, but there are some options:
1) adjust the existing images so they'll better fit in that space — which may include fading out the left half of them. Will test today.
2) download new images that are similar in content and visual, but a better fit for the new space
3) flip entirely to a solid left side purple gradient so we can afford to use a wider set of images. this would be a last resort, imo.

@matthewcrist OEC is gonna love how easy it is to set these! Some styling requests:
- Min height set to 300px to save some vertical space
- On mobile/tablet, can we set the gradient to cover the full width, or just use a full overlay? That'll make it less likely we'll run into color contrast issues on the right side of the screen
-  We'll want to tighten the space around breadcrumbs too. Once we see how the new style fits, we'll want to shrink the "margin-top-6" value to somewhere around 1.5-2rem. Will help the space on non-hero image headers too.

Dassit for now! Lookin good!

**Comment by admoorgit** [comment]
Hi!
A few minor things, but overall the header image works well across browsers. Here's what I found:

**IE11 on Windows 7 and 10** rolls back to the regular gradient (good!), but:

- Image gets squished on mobile (similar to what @AmeliaWellers saw in Safari)
![ie11-win10-mob.png](https://images.zenhubusercontent.com/60074627e5960a2e82af8ecd/233ed123-5de3-404a-bd97-5bf6819d6fef)

- @bloom-hondo is it possible to add some transparency to the gradient — like 5%? Or is that not supported in IE either? Not a huge issue if not; it blocks a bit of the image but it's not a deal breaker.

![ie11-win10.png](https://images.zenhubusercontent.com/60074627e5960a2e82af8ecd/caf111b5-2b90-4a86-906a-f839ec6c470d)

**Comment by bloom-hondo** [comment]
These updates are on staging @admoorgit and @AmeliaWellers

**Comment by AmeliaWellers** [comment]
@admoorgit Since you added all of the header images today, can you confirm that all product/design reccs work as expected/noted above? I did not add one, so I cannot confirm :)

**Comment by admoorgit** [comment]
All set! The only thing I haven't checked is "max image dimension / resolution" as I don't think we have a cap in place for that. Or do we, @matthewcrist ?
