### ISSUE TITLE
Build icon guide / add custom icons

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#88]
### Context
While assigning icons to callouts, it became clearer which icons don't need to be in the library. Additionally, the callout box functionality had some development limitations, leading to the necessity for an icon guide to be present in the Style Guide

### User Story
When someone wants to add an icon to a callout box, they can reference an icon library guide ctoec.org/oec-icons to assist with choosing the appropriate icon for their content. 

### Requirements
- icons grouped by theme (by request of the advisory team)
- any additional icons that don't serve a specific action or type of content are removed to avoid confusion
- icon titles match the titles in the icon library
- additional custom icons are added to the guide and the library

**Some ideas to get started**
For organizing icons, order by action
- on this page (list)
- Any type of announcement (megaphone)
- Any type of resource (phone, document, etc)
- Need Child Care? (kiddos)
- Time (clock, alarm)

needed: 
safety

**Comment by admoorgit** [comment]
Page is here: [OEC Icon Library](https://www.ctoec.org/oec-icon-library/)
Still in progress. Need to:
• add in all (custom) icons
• fix height issue w/ tables
• gain consensus on categories

**Comment by AmeliaWellers** [comment]
Thanks for the update! Let's touch base on your progress tomorrow during standup, happy to dedicated some focused time tomorrow to help with confirming the categories, aiming to finish by the end of the day/end of sprint.

**Comment by admoorgit** [comment]
[Custom icons added](https://www.ctoec.org/oec-icon-library/). Likely more to come as needed.
Next steps:

[ x ] - @AmeliaWellers and Adam to gain consensus on categories
[ x ] - Adam to update icon categories accordingly
[ ] - @bloom-hondo to add magic that adjusts table height based on category, or suggest alternative solution
[ x ] - Morgan to tweak intro content to align with the rest of the of the section
[ ] - Adam to put page in the proper place on the site, and add left nav

**Comment by admoorgit** [comment]
Updates were made per @AmeliaWellers and @MorganGriffin-BloomWorks 's feedback. Here's what changed:

- Agreed with Amelia's thoughts on categories. Only thing different is I added "Social"
- Added new intro content and callout box per Morgan's suggestions
- Gotta add the new categories and change a few icon cats, which I will get by tomorrow AM
- Then it will be ready for @bloom-hondo to work his magic and fix those table heights (icons are supposed to be 40x40 for the record)

Here's what Morgan suggested:
• The wrench means "this is a tool" or "fix a thing" right? I'd lean toward keeping where it is. **(Adam agrees)**
• Child care 2 — definitely keep. It's actually perfect for child care centers/schools vs. child care 1 (which looks like a family child care home). Could we actually rename the icons to "child care center/school" and "family child care home"? **(Adam agrees and fixed)**
• Also agree about keeping the ear for deaf etc. (Side note: Could we tag icons in some way so the ear would come up if someone searched for "deaf"?) **(Adam and Amelia agree)**
• I might also keep download. It could have a use. **(I'm agree with keeping it)** 
• Is there one we could use for a form? Online or PDF? That could be handy. **(added!)**


Dassit!
- a.

**Comment by admoorgit** [comment]
Howdy!
All changes made and categories refigured. @bloom-hondo it's all ready for you, now!

**Here are the categories for easy reference:**
action
announcements
child care
data and technology
documents and media
health
items
location
people and family
social

**Comment by MorganGriffin-BloomWorks** [comment]
Hey! This is looking good. @AmeliaWellers I improved a few suggestions about how to use them and will look again tomorrow to make them more formal. Just thinking guidance could be helpful or icons could wind up anywhere. Let me know if you have thoughts.
