### ISSUE TITLE
Mockup + Build News Widget on Stage Homepage

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#91]
### User Stories 
- As a user, I can click on a "Latest News" news post to view OEC's most recent news.

### Product Requirements
-   user can scroll down to the news widget on the homepage 
-   user can view a list of 3 (min) to 5 (max) news posts on the homepage 
-   user can click on any news post via a hyperlinked title
-   when user clicks on the title of a news post, they are sent to the news post
-   user can click to the ctoec.org/news homepage to view additional news items (optional)

### Design Requirements
- News widget nests between "build your career" and "About the OEC" website sections 
- User can see the date each news post was published
- Minimal customization should be required to maintain news widget long-term
- Fully accessible (Section 508c)

### Resources

[User Research July 2019](https://docs.google.com/presentation/d/1stlMKPucvTh97cLD1Y743exWP1Q3-WuW6E58g2vzVhw/edit#slide=id.g5e4967f363_0_156)
[Homepage and News Page Rationale](https://docs.google.com/document/d/1N4jmeKEmLAv_ukV0gxKtEDvlTJhJD0xUGJJVivzJJK0/edit)

Notes: 
- Proposed a Featured news feature to the Advisory team on 3/16/21, and they didn't take to it. So, the product requirements have been updated to not include featured news, and only list news chronologically. 
- Team decided not to propose categories or thumbnail images in the first iteration

# QA Checklist 
- [x] Amelia moves QA checklist to each user story/issue 
- [x] Round 1a: Amelia tests functions and as much accessibility as possible, report findings in ticket
- [ ] Round 1b: Adam tests functions and finishes accessibility checklist, report findings in ticket
- [ ] Round 2: Matt updates stage, Amelia and Adam confirm bug fixes in stage

## Product / Function
- [ ]  meets product requirements
- [ ]  meets design requirements 
- [ ]  meets acceptance criteria (user story) 
- [ ]  additional functions or use cases tested: 
  - [ ] 
  - [ ] 

## Accessibility
- [x] Site doesn't timeout unexpectedly
- [x] Default language is set
- [x] Page is keyboard accessible and free of keyboard traps
- [x] Page tab order is logical
- [x] Site never loses focus
- [x] Page titles are descriptive
- [x] Headings are nested properly
- [x] Text has sufficient color contrast
- [x] Links are unique and contextual
- [x] All relevant images use an “img” tag
- [x] All images have alt attributes
- [x] Multimedia is tagged
- [x] Tables are coded properly
- [x] Form inputs have explicit labels
- [x] Form instructions are associated with correct inputs
- [x] Frames (if applicable) are named
- [x] CSS isn't required to use the page
- [x] Flashing elements are compliant or set to static
- [x] Required plugins are linked on the page

### Mac
- [x] OS Catalina - Safari 13, Chrome 88, 87 (Amelia)
- [ ] OS Big Sur - Safari 14, Chrome 88, 87 (Adam)
### Windows 10 (Adam)
- [x] Edge 88
- [x] Safari 14, 13
- [x] Chrome 88, 87 
- [ ] IE 11
### iOS (Amelia)
- [ ] iPhone: 12, 12 Pro Max, XR, 11, 8, Mini SE
  - [ ] Safari 14, 13
  - [ ] Chrome 88, 87 
- [ ] iPad 12 (check resolution!)
  - [ ] Safari 14, 13
  - [ ] Chrome 88, 87 
### Android (Adam) 
- [ ] Galaxy S9

### Full accessibility checklist
https://skylight.digital/work/toolkits/accessibility-guide/checklist/

**Comment by admoorgit** [comment]
HOWDY!
Here are previous versions of the news widget from Figma!

This was done before I came on board, so early 2020:
![image.png](https://images.zenhubusercontent.com/60074627e5960a2e82af8ecd/9a9abe94-8128-49ad-9f5b-9e2e95e2ada9)


Here's the basic one we pulled together in Oct 2020:
![image.png](https://images.zenhubusercontent.com/60074627e5960a2e82af8ecd/d57f9262-2aa0-41cd-8567-c3cf1cdf2a2c)


As we've since made the new CTDS callout boxes, we conceivably could pull those in to make the featured news more substantive visually. At the time (oct 2020) we were looking at MVPs before the contract was out, but since we have an actual sprint here, we could def do more. Within reason, of course.

**Comment by AmeliaWellers** [comment]
Notes from the advisory meeting today:
- We proposed a Featured news feature to the Advisory team on 3/16/21. They didn't take to it and preferred chronological (including when a featured news post was positioned as an alternative to the Home Visiting RFP callout). So, the requirements have been updated to not include featured news, and only list news chronologically. 
- Team decided not to propose categories or thumbnail images in the first iteration for the sake of simplicity.

Outstanding questions:
- How to address "published" vs "last updated"
- Need to remove the "Featured Post" Block in the News section

**Comment by AmeliaWellers** [comment]
My first round of notes: 
- Bring the News one section higher on the homepage: below "build your career" and above Beth's blue section. 
- Change title on the homepage: "Read the latest news from OEC" and remove the help text. 
- Have "See All News" match the size and type of the other links on the page. 
- Reduce either the width or the padding of the news Icon by about 20 pixels, to reduce the space between the icon and the "See All news" hyperlink

I believe we had discussed not displaying categories on the homepage. Imo, since a user can't interact with them, they don't make much sense out of context of the filtered news page. Is this a big lift to remove? If not, let's remove the categories.

**Comment by AmeliaWellers** [comment]
Two more design things:
-  I'm not the best at estimating pixels, but I think the space under the "Latest News" H2 and the title of the first news post should total about 26.5 pixels (identical to the space below the H2s in the section before it). 
- Digging into my "have see all news" comment above: there's now a discrepancy between 2 different link styles on the homepage (screenshots to illustrate). My sense is that all link text color should be similar to the "Latest News" color #2378c3 and the size should be 14pt font. Since this change would not be specific to the news feed, I can make a new ticket if Matt desires. 

![Screen Shot 2021-04-05 at 4.40.57 PM.png](https://images.zenhubusercontent.com/600707487eacdcc9a535ffa4/9a3797eb-6d76-47af-a106-de06e9ff37e8)![Screen Shot 2021-04-05 at 4.40.33 PM.png](https://images.zenhubusercontent.com/600707487eacdcc9a535ffa4/0371419a-1bf0-48e1-a5a2-c4fb69a22f5d)

**Comment by admoorgit** [comment]
Hello!
Noticed the mock on here is OLD — not sure where the new one is on here (if its even on here), but here it is: 
![Homepage News.jpg](https://images.zenhubusercontent.com/60074627e5960a2e82af8ecd/580e9f05-b2ec-497a-b34d-819ca345005e)

Re: link color — @bloom-hondo it should be whatever we're using across the site.
Re: spacing — it'll match whatever is across the site. Figma is more of a representation of what'll be on the site, but may differ in some of those minor tweaks that we make once it's on the site. Figma, for instance, uses PX as size, but we use REM on the site, so there's a little bit of math involved.

- a.

**Comment by AmeliaWellers** [comment]
@bloom-hondo wanted to make sure you saw Adam's mockup above. The main changes are
-  to raise the full news section ABOVE the "About the Office of Early Childhood" section
-  shrink the section from 5 news article links to 3 news article links

Also, the link changes look much better, as well as the link consistency on the homepage. Thanks for popping in Adam but also go have fun with your child.

**Comment by AmeliaWellers** [comment]
**Cosmetic thing:** In Chrome/desktop devices, sections of the link's on-click blue border are covered by the grid container 

![Screen Shot 2021-04-08 at 5.23.48 PM.png](https://images.zenhubusercontent.com/600707487eacdcc9a535ffa4/552ae7fe-b896-411b-ac4c-90fc2c9206fd)![Screen Shot 2021-04-08 at 5.23.31 PM.png](https://images.zenhubusercontent.com/600707487eacdcc9a535ffa4/1c193189-da28-4cee-9076-da17712f7f5d)

**Comment by AmeliaWellers** [comment]
**Issue**:  In Chrome/desktop devices, no blue border shows when tabbing to or clicking "See All News"
**Suggested fix**: Ensure blue border visible when tabbed through or clicked, if only for consistency purposes.

**Comment by AmeliaWellers** [comment]
It's live! Notes for @bloom-hondo 
- The "New" has resurfaced! It wasn't there in the staging site and we didn't share this design with OEC. Even though it does give the page a nice visual balance, I think we should remove. One less thing that OEC will need to think about on their homepage (or try to change once we've left). 
- Adam's mockup has all H1s in purple. We currently have two titles in blue and one in purple. Let's turn these all purple (if it's easy). 
- Add a period after "Read the latest news from OEC**.**" For consistency with other titles.

**Comment by bloom-hondo** [comment]
All set. The headline is editable in WP on the home page just FYI.

**Comment by AmeliaWellers** [comment]
This looks great! I'll move the Chrome blue tab border cosmetic issue, as well as a few non-widget-specific bugs, into a "homepage issues" ticket for the next sprint. Other than that, this is looking really nice.
