### ISSUE TITLE
Misaligned image in Media & Text Block

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#94]
**Describe the bug**
When an image is justified to the top of the screen within the Media and Text block, image do not line up with the text. Currently, this is being used on the [History of the Parent Cabinet](https://www.ctoec.org/about-oec/partnerships/parent-cabinet/parent-cabinet-history/) page. 

**Expected behavior**
Top border of image horizontally aligns with top line of text. (Line between bios are there for demonstration, but ideally, don't stay there long-term).

**Screenshots**
![Screen Shot 2021-03-08 at 5.21.14 PM.png](https://images.zenhubusercontent.com/600707487eacdcc9a535ffa4/cce7fae4-1caf-4e72-b579-b93bb39fdaa7)

**Comment by admoorgit** [comment]
Hello!
To make this adjustment we'd need to tweak the "Media & Text" block in WP. Currently, content has a margin block above and below it, and the image doesn't.

**If we add margin-top: 1.6rem; to .wp-block-media-test_media img, the text and image will top align.**
![image.png](https://images.zenhubusercontent.com/60074627e5960a2e82af8ecd/62f24b36-546b-4904-a722-a1445bab4692)

Here's a screenshot with that margin added:
![image.png](https://images.zenhubusercontent.com/60074627e5960a2e82af8ecd/05747a9f-6931-4e2b-b26f-4102ca7f47fa)


@bloom-hondo, is this something you can do?

- a.
