### ISSUE TITLE
CTOEC Body shifting to the right on Edge for Windows in Browserstack

### ISSUE THREAD

**Issue by admoorgit** [matthewcrist/ctoec#95]
Something to look into, as I'm not sure it's a Browserstack or Windows/Edge 88/89 issue.

There are times when a page on CTOEC.org will load with the body content shifted entirely over to the right. It's about the same width of the left nav. It's not consistent, and sometimes it cleans up after a refresh. It may not be anything, but wanted to flag it none-the-less.

![image.png](https://images.zenhubusercontent.com/60074627e5960a2e82af8ecd/d13bea48-36b5-4833-8766-71a6c51b23a7)

**Comment by AmeliaWellers** [comment]
Discussed 3/22: This is a browserstack issue
